"use server";

import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const API_BASE = process.env.API_URL || "http://localhost:8000";
const FRONTEND_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

/**
 * OAuth 로그인 - 사용자를 OAuth 제공자 인증 페이지로 리다이렉트
 */
export async function signInWithOAuth(
  provider: "google" | "kakao",
  callbackUrl = "/"
): Promise<void> {
  // callbackUrl을 임시 쿠키에 저장 (redirect_uri에 포함하면 Google Console 등록 URI와 불일치)
  const cookieStore = await cookies();
  cookieStore.set("auth-callback-url", callbackUrl, {
    path: "/",
    maxAge: 600,
    httpOnly: true,
    sameSite: "lax",
  });

  const redirectUri = `${FRONTEND_URL}/api/auth/callback/${provider}`;

  /*
    https://accounts.google.com/o/oauth2/v2/auth
    ?client_id=YOUR_GOOGLE_CLIENT_ID    ← added by backend
    &redirect_uri=http://localhost:3000/api/auth/callback/google ← redirect URI is the URL the user is redirected to after the provider grants consent
    &scope=email+profile                  ← scope is the permissions the user is granting to the app
    &state=random_csrf_token              ← added by backend and echoed back by the provider in the callback
    &response_type=code                   ← response type is the type of response the user is requesting from the provider
  */

  const res = await fetch(
    `${API_BASE}/api/v1/auth/oauth/${provider}/authorize?redirect_uri=${encodeURIComponent(redirectUri)}`
  );

  if (!res.ok) {
    throw new Error("Failed to get authorization URL");
  }

  const data = await res.json();
  // redirect the user to the OAuth provider's consent page
  // this URL is generated by the backend and contains the Client ID and Redirect URI
  // the user is redirected to this URL to grant consent to the app
  redirect(data.url);
}
